-- service_accounting_statement
-- CREATE DATABASE IF NOT EXISTS service_accounting_statement DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
-- USE service_accounting_statement;

CREATE TABLE account (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 merchant_id bigint NOT NULL COMMENT 'fk',
 trade_merchant_id varchar(64) NULL COMMENT 'ref:trading system merchantId',
 country_code varchar(2) NOT NULL COMMENT 'CountryCodeEnum',
 transaction_type_code varchar(32) NOT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
 latest_daily_balance decimal(26, 0) NULL DEFAULT 0 COMMENT 'Yesterday`s balance',
 sub_total_amount decimal(26, 0) NULL DEFAULT 0 COMMENT 'Amount of the day',
 currency varchar(3) NULL DEFAULT NULL COMMENT 'balance pool currency properties',
 source_currency varchar(255) NULL DEFAULT NULL COMMENT 'format:Comma segmentation, like USD,MXN,BRL',
 timezone varchar(8) NULL DEFAULT NULL COMMENT 'local time zone',
 timezone_name varchar(64) NULL DEFAULT '',
 created_time datetime NULL DEFAULT NULL,
 updated_time datetime NULL DEFAULT NULL,
 created_by bigint NULL DEFAULT 0,
 updated_by bigint NULL DEFAULT 0,
 version bigint UNSIGNED NULL DEFAULT 1 COMMENT 'optimistic locking',
 del_flag tinyint(1) NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 INDEX idx_merchant_id(merchant_id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'account' ROW_FORMAT = DYNAMIC;


CREATE TABLE account_daily_bill (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 account_id bigint NOT NULL COMMENT 'fk',
 merchant_id bigint NULL DEFAULT NULL,
 country_code varchar(3) NULL DEFAULT NULL COMMENT 'CountryCodeEnum',
 transaction_type_code varchar(32) NULL DEFAULT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
 bill_timestamp timestamp NOT NULL COMMENT 'timestamp',
 timezone varchar(8) NOT NULL,
 bill_month int NOT NULL COMMENT 'yyyyMM',
 bill_date date NOT NULL COMMENT 'yyyyMMdd',
 topup_count int UNSIGNED NULL DEFAULT 0,
 topup_amount decimal(26, 0) NULL DEFAULT 0 COMMENT 'amount of the transaction current day',
 topup_fee decimal(26, 0) NULL DEFAULT 0,
 topup_tax decimal(26, 0) NULL DEFAULT 0,
 transaction_count int UNSIGNED NULL DEFAULT 0 COMMENT 'number of transactions current day',
 transaction_amount decimal(26, 0) NULL DEFAULT 0,
 transaction_fee decimal(26, 0) NULL DEFAULT 0,
 transaction_tax decimal(26, 0) NULL DEFAULT 0,
 transfer_count int NULL DEFAULT 0,
 transfer_amount decimal(26, 0) NULL DEFAULT 0,
 transfer_fee decimal(26, 0) NULL DEFAULT 0,
 transfer_tax decimal(26, 0) NULL DEFAULT 0,
 refund_count int NULL DEFAULT 0,
 refund_amount decimal(26, 0) NULL DEFAULT 0,
 refund_fee decimal(26, 0) NULL DEFAULT 0,
 refund_tax decimal(26, 0) NULL DEFAULT 0,
 start_balance decimal(26, 0) NULL DEFAULT 0,
 happen_amount decimal(26, 0) NULL DEFAULT 0,
 end_balance decimal(26, 0) NULL DEFAULT 0,
 fx_rate decimal(26, 6) NULL DEFAULT 0.000000 COMMENT 'exchange rate for settlement current day',
 created_time datetime NULL DEFAULT NULL,
 updated_time datetime NULL DEFAULT NULL,
 created_by bigint NULL DEFAULT 0,
 updated_by bigint NULL DEFAULT 0,
 version int NULL DEFAULT 1 COMMENT 'optimistic locking',
 del_flag tinyint NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 UNIQUE INDEX idx_account_id(account_id, bill_date) USING BTREE,
 INDEX idx_merchant_id(merchant_id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'account_daily_bill' ROW_FORMAT = Dynamic;


CREATE TABLE account_daily_report (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 account_id bigint NOT NULL COMMENT 'fk',
 merchant_id bigint NULL DEFAULT NULL,
 bill_timestamp timestamp NOT NULL COMMENT 'timestamp',
 timezone varchar(8) NOT NULL,
 bill_type varchar(20) NULL DEFAULT NULL,
 bill_month int NOT NULL COMMENT 'yyyyMM',
 bill_date date NOT NULL COMMENT 'yyyyMMdd',
 total_count int UNSIGNED NULL DEFAULT 0,
 file_name varchar(255) NULL DEFAULT NULL,
 file_path varchar(255) NULL DEFAULT '0.000000' COMMENT 'exchange rate for settlement current day',
 file_size bigint UNSIGNED NULL DEFAULT 0 COMMENT 'unit: KB',
 created_time datetime NULL DEFAULT NULL,
 updated_time datetime NULL DEFAULT NULL,
 version int NULL DEFAULT 1 COMMENT 'optimistic locking',
 del_flag tinyint NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 INDEX idx_account_id(account_id) USING BTREE,
 INDEX idx_merchant_id(merchant_id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'account_daily_bill' ROW_FORMAT = Dynamic;


CREATE TABLE account_statement (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 account_id bigint NOT NULL,
 transaction_id bigint NOT NULL COMMENT 'fk tack_id',
 transaction_type_code varchar(32) NULL DEFAULT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
 product_code varchar(32) NULL DEFAULT NULL COMMENT 'ProductCodeEnum',
 business_type varchar(32) NULL DEFAULT NULL COMMENT 'business_type : TRANSACTION, TOPUP, TRANSFER_OUT, REFUND',
 direction_type varchar(32) NULL DEFAULT NULL COMMENT 'DirectionTypeEnum: SETTLED/REFUND/CHARGE_BACK',
 amount_pon decimal(2, 0) NULL DEFAULT NULL COMMENT 'positive or negative; positive :+1, negative:-1',
 amount decimal(26, 0) NULL DEFAULT NULL COMMENT 'save integer type, default to penny',
 currency varchar(3) NULL DEFAULT NULL,
 start_balance decimal(26, 0) NULL DEFAULT NULL,
 end_balance decimal(26, 0) NULL DEFAULT NULL,
 transaction_time timestamp NULL DEFAULT NULL,
 settle_time timestamp NULL DEFAULT NULL,
 created_time datetime NULL DEFAULT CURRENT_TIMESTAMP,
 updated_time datetime NULL DEFAULT CURRENT_TIMESTAMP,
 created_by bigint NULL DEFAULT NULL,
 updated_by bigint NULL DEFAULT NULL,
 version int NULL DEFAULT 1 COMMENT 'optimistic locking',
 del_flag tinyint NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 INDEX idx_account_id(account_id) USING BTREE,
 INDEX idx_transaction_id(transaction_id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'account_statement' ROW_FORMAT = Dynamic;

CREATE TABLE biz_refund (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 transaction_id bigint NOT NULL,
 merchant_id bigint NOT NULL,
 account_id bigint NOT NULL COMMENT 'fk_account',
 reference_id varchar(64) NULL DEFAULT NULL,
 opposite_name varchar(64) NULL DEFAULT NULL,
 transaction_time timestamp NULL DEFAULT NULL,
 transaction_type_code varchar(32) NULL DEFAULT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
 amount decimal(26, 0) NULL DEFAULT NULL COMMENT 'save integer type, default to penny',
 currency varchar(3) NULL DEFAULT NULL,
 fx_rate decimal(26, 6) NULL DEFAULT NULL,
 settlement_amount decimal(26, 0) NULL DEFAULT NULL,
 settlement_currency varchar(3) NULL DEFAULT NULL,
 fee decimal(26, 0) NULL DEFAULT NULL,
 tax decimal(26, 0) NULL DEFAULT NULL,
 settle_status varchar(32) NULL DEFAULT 'WAITING' COMMENT 'StatusEnum: WAITING/PROCESSING/SUCCESS/FAILED',
 comments varchar(400) NULL DEFAULT NULL,
 created_time datetime NULL DEFAULT NULL,
 updated_time datetime NULL DEFAULT NULL,
 created_by bigint NULL DEFAULT 0,
 updated_by bigint NULL DEFAULT 0,
 bill_id bigint UNSIGNED NULL DEFAULT NULL COMMENT 'reference account_daily_bill.id',
 version int NULL DEFAULT 1 COMMENT 'optimistic locking',
 del_flag tinyint(1) NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 UNIQUE INDEX udx_transaction_id(transaction_id) USING BTREE,
 INDEX idx_merchant_account_id(merchant_id, account_id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'biz_refund' ROW_FORMAT = Dynamic;


CREATE TABLE biz_topup (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 transaction_id bigint NOT NULL,
 merchant_id bigint NOT NULL,
 account_id bigint NOT NULL COMMENT 'fk_account',
 transaction_time timestamp NULL DEFAULT NULL,
 transaction_type_code varchar(32) NULL DEFAULT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
 amount decimal(26, 0) NULL DEFAULT NULL COMMENT 'save integer type, default to penny',
 currency varchar(3) NULL DEFAULT NULL,
 fx_rate decimal(26, 6) NULL DEFAULT NULL,
 settlement_amount decimal(26, 0) NULL DEFAULT NULL,
 settlement_currency varchar(3) NULL DEFAULT NULL,
 fee decimal(26, 0) NULL DEFAULT NULL,
 tax decimal(26, 0) NULL DEFAULT NULL,
 settle_status varchar(32) NULL DEFAULT 'WAITING' COMMENT 'StatusEnum: WAITING/PROCESSING/SUCCESS/FAILED',
 comments varchar(400) NULL DEFAULT NULL,
 created_time datetime NULL DEFAULT NULL,
 updated_time datetime NULL DEFAULT NULL,
 created_by bigint NULL DEFAULT 0,
 updated_by bigint NULL DEFAULT 0,
 version int NULL DEFAULT 1 COMMENT 'optimistic locking',
 bill_id bigint UNSIGNED NULL DEFAULT 0 COMMENT 'reference account_daily_bill.id',
 del_flag tinyint(1) NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 UNIQUE INDEX udx_transaction_id(transaction_id) USING BTREE,
 INDEX idx_merchant_account_id(merchant_id, account_id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'biz_refund' ROW_FORMAT = Dynamic;


CREATE TABLE biz_transfer_out (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 transaction_id bigint NOT NULL,
 merchant_id bigint NOT NULL,
 account_id bigint NOT NULL COMMENT 'fk_account',
 transaction_time timestamp NULL DEFAULT NULL,
 transaction_type_code varchar(32) NULL DEFAULT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
 amount decimal(26, 0) NULL DEFAULT NULL COMMENT 'save integer type, default to penny',
 currency varchar(3) NULL DEFAULT NULL,
 fx_rate decimal(26, 6) NULL DEFAULT NULL,
 settlement_amount decimal(26, 0) NULL DEFAULT NULL,
 settlement_currency varchar(3) NULL DEFAULT NULL,
 fee decimal(26, 0) NULL DEFAULT NULL,
 tax decimal(26, 0) NULL DEFAULT NULL,
 settle_status varchar(32) NULL DEFAULT 'WAITING' COMMENT 'StatusEnum: WAITING/PROCESSING/SUCCESS/FAILED',
 comments varchar(400) NULL DEFAULT NULL,
 created_time datetime NULL DEFAULT NULL,
 updated_time datetime NULL DEFAULT NULL,
 created_by bigint NULL DEFAULT 0,
 updated_by bigint NULL DEFAULT 0,
 version int NULL DEFAULT 1 COMMENT 'optimistic locking',
 bill_id bigint UNSIGNED NULL DEFAULT 0 COMMENT 'reference account_daily_bill.id',
 del_flag tinyint(1) NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 UNIQUE INDEX udx_transaction_id(transaction_id) USING BTREE,
 INDEX idx_merchant_account_id(merchant_id, account_id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'biz_refund' ROW_FORMAT = Dynamic;


CREATE TABLE transaction_fee (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 transaction_id bigint NOT NULL COMMENT 'fk tack_id',
 merchant_id bigint NOT NULL COMMENT 'fk',
 account_id bigint NOT NULL COMMENT 'fk',
 monthly_fee_configuration_id bigint NOT NULL COMMENT 'fk',
 transaction_type_code varchar(32) NULL DEFAULT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
 product_code varchar(32) NULL DEFAULT NULL COMMENT 'ProductEnum',
 fee_type_code varchar(32) NULL DEFAULT NULL COMMENT 'FeetypeEnum',
 amount_pon decimal(2, 0) NOT NULL COMMENT 'positive or negative; positive :+1, negative:-1',
 settlement_amount decimal(26, 0) NULL DEFAULT NULL,
 settlement_currency varchar(3) NULL DEFAULT NULL,
 instant_flag tinyint(1) NULL DEFAULT 0 COMMENT '0-non-instant，1-instant',
 transaction_time timestamp NOT NULL COMMENT 'original task_fee_calculation.transaction_time UTC+0',
 settle_status varchar(32) NULL DEFAULT NULL COMMENT 'StatusEnum: WAITING/PROCESSING/SUCCESS/FAILED',
 settle_time timestamp NULL DEFAULT NULL,
 created_time datetime NULL DEFAULT NULL,
 updated_time datetime NULL DEFAULT NULL,
 created_by bigint NULL DEFAULT 0,
 updated_by bigint NULL DEFAULT 0,
 version int NULL DEFAULT 1 COMMENT 'optimistic locking',
 bill_id bigint UNSIGNED NULL DEFAULT 0 COMMENT 'reference account_daily_bill.id',
 del_flag tinyint(1) NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 INDEX idx_merchant_account_id(merchant_id, account_id) USING BTREE,
 INDEX idx_transaction_id(transaction_id) USING BTREE,
 INDEX idx_transaction_time(transaction_time) USING BTREE,
 INDEX idx_bill_id(bill_id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'transaction_fee' ROW_FORMAT = Dynamic;


CREATE TABLE transaction_money (
 id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
 transaction_id bigint NOT NULL COMMENT 'fk tack_id',
 merchant_id bigint NOT NULL COMMENT 'fk',
 account_id bigint NOT NULL,
 transaction_type_code varchar(32) NULL DEFAULT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
 product_code varchar(32) NULL DEFAULT NULL COMMENT 'ProductCodeEnum: SPEI/TED/PIX/CREDIT_CARD/ELO_CREDIT_CARD/BOLETO/OXXO/GIFTCARD/TOPUP/UTILITY',
 direction_type varchar(32) NULL DEFAULT NULL COMMENT 'DirectionTypeEnum: SETTLED/REFUND/CHARGE_BACK',
 amount_pon decimal(2, 0) NOT NULL COMMENT 'positive or negative; positive :+1, negative:-1',
 amount decimal(26, 0) NULL DEFAULT NULL,
 currency varchar(3) NULL DEFAULT NULL,
 fx_rate decimal(26, 6) NULL DEFAULT NULL,
 settlement_amount decimal(26, 0) NULL DEFAULT NULL,
 settlement_currency varchar(3) NULL DEFAULT NULL,
 transaction_time timestamp NOT NULL COMMENT 'original task_fee_calculation.transaction_time UTC+0',
 settle_time timestamp NULL DEFAULT NULL,
 settle_status varchar(32) NULL DEFAULT NULL COMMENT 'StatusEnum: WAITING/PROCESSING/SUCCESS/FAILED',
 extend_data json NULL,
 created_time datetime NULL DEFAULT NULL,
 updated_time datetime NULL DEFAULT NULL,
 created_by bigint NULL DEFAULT 0,
 updated_by bigint NULL DEFAULT 0,
 version int NULL DEFAULT 1 COMMENT 'optimistic locking',
 bill_id bigint UNSIGNED NULL DEFAULT 0 COMMENT 'reference account_daily_bill.id',
 del_flag tinyint(1) NULL DEFAULT 0 COMMENT '0-normal，1-delete',
 remark varchar(200) NULL DEFAULT '' COMMENT 'remark',
 PRIMARY KEY (id) USING BTREE,
 UNIQUE INDEX udx_transaction_id(transaction_id) USING BTREE,
 INDEX idx_merchant_account_id(merchant_id, account_id) USING BTREE,
 INDEX idx_bill_id(bill_id) USING BTREE,
 INDEX idx_transaction_time(transaction_time) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'transaction_month' ROW_FORMAT = Dynamic;
