CREATE TABLE `transaction_cost_extra`
(
    `id`                      bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'transaction cost extra ID',
    `bill_id`                 bigint unsigned NOT NULL DEFAULT '0' COMMENT 'bill Id',
    `country_code`            varchar(3)     NOT NULL COMMENT 'Country code',
    `merchant_code`           varchar(32)    NOT NULL COMMENT 'Merchant code',
    `merchant_id`             bigint         NOT NULL COMMENT 'Merchant id',
    `account_id`              bigint         NOT NULL COMMENT 'AccountId',
    `fee_usd`                 decimal(26, 6) NOT NULL DEFAULT '0.000000' COMMENT 'Transaction fee Amount converted into USD, Unit: cent',
    `extra_fee_usd`           decimal(26, 6)          DEFAULT '0.000000' COMMENT 'Extra Transaction Fee Amount converted into USD, Unit: cent',
    `tax_usd`                 decimal(26, 6) NOT NULL DEFAULT '0.000000' COMMENT 'Tax Amount converted into USD, Unit: cent',
    `extra_tax_usd`           decimal(26, 6)          DEFAULT '0.000000' COMMENT 'Extra Transaction Tax Amount converted into USD, Unit: cent',
    `fx_usd`                  decimal(26, 6) NOT NULL DEFAULT '0.000000' COMMENT 'Fx Amount converted into USD, Unit: cent',
    `extra_fx_usd`            decimal(26, 6)          DEFAULT '0.000000' COMMENT 'Extra Transaction FX Amount converted into USD, Unit: cent',
    `cost_fee`                decimal(26, 6) NOT NULL DEFAULT '0.000000' COMMENT 'Cost Fee(USD), Unit: cent',
    `cost_tax`                decimal(26, 6) NOT NULL DEFAULT '0.000000' COMMENT 'Cost Tax(USD), Unit: cent',
    `cost_fx`                 decimal(26, 6) NOT NULL DEFAULT '0.000000' COMMENT 'Cost FX(USD), Unit: cent',
    `cost_other`              decimal(26, 6) NOT NULL DEFAULT '0.000000' COMMENT 'Other cost(USD) besides costFee, costTax, costFx. Unit: cent',
    `currency`                varchar(3)     NOT NULL COMMENT 'Currency',
    `extra_record_year`       int            NOT NULL COMMENT 'Year of recordDate',
    `extra_record_year_month` int            NOT NULL COMMENT 'Month of recordDate',
    `extra_record_year_week`  int            NOT NULL COMMENT 'Week of recordDate',
    `extra_record_date`       date           NOT NULL COMMENT 'Date of recordDate',
    `submit_time`             datetime                DEFAULT NULL COMMENT 'record submit time',
    `created_time`            datetime                DEFAULT NULL COMMENT 'created time',
    `updated_time`            datetime                DEFAULT NULL COMMENT 'updated time',
    `created_by`              bigint                  DEFAULT '0' COMMENT 'created by',
    `updated_by`              bigint                  DEFAULT '0' COMMENT 'updated by',
    `version`                 int            NOT NULL DEFAULT '1' COMMENT 'Optimistic locking flag',
    `del_flag`                tinyint(1) NOT NULL DEFAULT '0' COMMENT 'DelFlag 0:normal; 1:delete',
    `remark`                  varchar(200)            DEFAULT '' COMMENT 'remark',
    PRIMARY KEY (`id`),
    KEY                       `idx_account_bill` (`account_id`,`bill_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='transaction_cost_extra';