CREATE TABLE service_accounting_statement.transaction_cost_extra
(
    id                    bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'transaction cost extra ID',
    business_tag          varchar(40) NULL DEFAULT 'DEFAULT' COMMENT 'Business Tag',
    country_code          varchar(3)  NOT NULL COMMENT 'Country code',
    merchant_code         varchar(32) NOT NULL COMMENT 'Merchant code',
    merchant_id           bigint      NOT NULL COMMENT 'Merchant id',
    account_id            bigint      NOT NULL COMMENT 'AccountId',
    bill_id               bigint unsigned NOT NULL DEFAULT '0' COMMENT 'bill Id',
    bill_date             date        NOT NULL COMMENT 'bill date with account timezone',
    fee_usd               decimal(26, 0) DEFAULT '0' COMMENT 'Transaction fee Amount converted into USD, Unit: cent',
    tax_usd               decimal(26, 0) DEFAULT '0' COMMENT 'Tax Amount converted into USD, Unit: cent',
    fx_usd                decimal(26, 0) DEFAULT '0' COMMENT 'Fx Amount converted into USD, Unit: cent',
    extra_fee_usd         decimal(26, 0) DEFAULT '0' COMMENT 'Extra Transaction Fee Amount converted into USD, Unit: cent',
    extra_tax_usd         decimal(26, 0) DEFAULT '0' COMMENT 'Extra Transaction Tax Amount converted into USD, Unit: cent',
    extra_fx_usd          decimal(26, 0) DEFAULT '0' COMMENT 'Extra Transaction FX Amount converted into USD, Unit: cent',
    exchange_fee_usd      decimal(26, 0) DEFAULT '0' COMMENT 'Exchange fee usd',
    cdi_profit_income_usd decimal(26, 0) DEFAULT '0' COMMENT 'Certificate of Deposit Interbank profit usd, Unit: cent',
    adjustment_fee_usd    decimal(26, 0) DEFAULT '0' COMMENT 'Adjustment fee usd, Unit: cent',
    cost_fee              decimal(26, 0) DEFAULT '0' COMMENT 'Cost Fee(USD), Unit: cent',
    cost_tax              decimal(26, 0) DEFAULT '0' COMMENT 'Cost Tax(USD), Unit: cent',
    cost_fx               decimal(26, 0) DEFAULT '0' COMMENT 'Cost FX(USD), Unit: cent',
    currency              varchar(3)  NOT NULL COMMENT 'Currency',
    created_time          datetime    NOT NULL COMMENT 'created time',
    updated_time          datetime    NOT NULL COMMENT 'updated time',
    created_by            bigint         DEFAULT '0' COMMENT 'created by',
    updated_by            bigint         DEFAULT '0' COMMENT 'updated by',
    version               int            DEFAULT '1' COMMENT 'Optimistic locking flag',
    del_flag              tinyint(1) DEFAULT '0' COMMENT 'DelFlag 0:normal; 1:delete',
    remark                varchar(200)   DEFAULT '' COMMENT 'remark',
    PRIMARY KEY (id),
    KEY                   idx_account_bill_id (account_id,bill_id) USING BTREE,
    KEY                   idx_account_bill_date (account_id,bill_date) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='transaction_cost_extra';