CREATE TABLE batch_withdrawal_apply
(
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
    batch_id            BIGINT          NOT NULL COMMENT 'batch id',
    merchant_id         BIGINT          NOT NULL COMMENT 'FK ref: merchant.id',
    account_id          BIGINT          NOT NULL COMMENT 'FK ref: account.id',
    sub_merchant_id     VARCHAR(128)    NOT NULL COMMENT 'FK ref: sub_merchant_info.sub_merchant_id',
    sub_merchant_name   VARCHAR(128)    NOT NULL COMMENT 'sub merchant name',
    sub_account_id      BIGINT          NOT NULL COMMENT 'FK ref:sub_account.id',
    withdrawal_amount   DECIMAL(26, 0)  DEFAULT '0' COMMENT 'withdrawal amount, unit:cent',
    transaction_count   INT UNSIGNED    DEFAULT '0' COMMENT 'transaction count of the day',
    fee_amount          DECIMAL(26, 0)  DEFAULT '0' COMMENT 'fee amount, unit:cent',
    tax_amount          DECIMAL(26, 0)  DEFAULT '0' COMMENT 'tax amount, unit:cent',
    settlement_currency VARCHAR(3)      NOT NULL COMMENT 'settlement currency',
    account_type        VARCHAR(32)     NULL DEFAULT '' COMMENT 'account type',
    account_name        VARCHAR(128)    NULL DEFAULT '' COMMENT 'account name',
    account_number      VARCHAR(128)    NULL DEFAULT '' COMMENT 'account number',
    apply_date          DATE            NOT NULL COMMENT 'withdrawal transaction apply date',
    completed_date      DATE            DEFAULT NULL COMMENT 'withdrawal transaction apply date',
    completed_time      DATETIME        DEFAULT NULL COMMENT 'withdrawal transaction apply datetime',
    state               TINYINT (4)     NOT NULL COMMENT 'state: 0: init; 1: processing; 2:success; 3: fail;',
    created_time        DATETIME        DEFAULT NULL COMMENT 'created time',
    updated_time        DATETIME        DEFAULT NULL COMMENT 'updated time',
    created_by          BIGINT          DEFAULT '0' COMMENT 'created by',
    updated_by          BIGINT          DEFAULT '0' COMMENT 'created by',
    version             BIGINT UNSIGNED DEFAULT '1' COMMENT 'optimistic locking',
    del_flag            TINYINT (1)     NOT NULL DEFAULT '0' COMMENT 'delFlag: 0-normal，1-delete',
    remark              VARCHAR(200)    DEFAULT '' COMMENT 'remark',
    PRIMARY KEY (id) USING BTREE,
    KEY                 idx_batch_id ( batch_id ) USING BTREE,
    KEY                 idx_sub_merchant_id ( sub_merchant_id ) USING BTREE,
    KEY                 idx_sub_account_id ( sub_account_id ) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'customize batch withdrawal apply(byd)';

CREATE TABLE batch_withdrawal_detail
(
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
    batch_id            BIGINT          NOT NULL COMMENT 'FK ref: batch_withdrawal_apply.batch_id',
    transaction_id      BIGINT          NOT NULL COMMENT 'FK ref: task_fee_calculation.id',
    unique_id           VARCHAR(128)    NOT NULL COMMENT 'unique id',
    merchant_id         BIGINT          NOT NULL COMMENT 'FK ref: merchant.id',
    sub_merchant_id     VARCHAR(128)    NOT NULL COMMENT 'FK ref: sub_merchant_info.sub_merchant_id',
    sub_merchant_name   VARCHAR(128)    NOT NULL COMMENT 'FK ref: sub_merchant.name',
    account_id          BIGINT          NOT NULL COMMENT 'FK ref: account.id',
    sub_account_id      BIGINT          NOT NULL COMMENT 'FK ref: sub_account.id',
    direction_type      varchar(32)     NOT NULL COMMENT 'DirectionTypeEnum: SETTLED/REFUND/CHARGE_BACK',
    credited_amount     DECIMAL(26, 0)  DEFAULT '0' COMMENT 'credited amount, unit:cent',
    settlement_currency VARCHAR(3)      DEFAULT NULL COMMENT 'settlement currency',
    credited_date       DATE            NOT NULL COMMENT 'credited date, unit:cent',
    apply_date          DATE            NOT NULL COMMENT 'apply date',
    completed_date      DATE            DEFAULT NULL COMMENT 'completed date',
    completed_time      DATETIME        DEFAULT NULL COMMENT 'completed datetime',
    state               TINYINT (4)     NOT NULL COMMENT 'state: 0: init; 1: processing; 2:success; 3: fail;',
    created_time        DATETIME        DEFAULT NULL COMMENT 'created time',
    updated_time        DATETIME        DEFAULT NULL COMMENT 'updated time',
    created_by          BIGINT          DEFAULT '0' COMMENT 'created by',
    updated_by          BIGINT          DEFAULT '0' COMMENT 'created by',
    version             BIGINT UNSIGNED DEFAULT '1' COMMENT 'optimistic locking',
    del_flag            TINYINT (1)     NOT NULL DEFAULT '0' COMMENT 'delFlag: 0-normal，1-delete',
    remark              VARCHAR(200)    DEFAULT '' COMMENT 'remark',
    PRIMARY KEY (id) USING BTREE,
    UNIQUE KEY udx_order_t ( transaction_id, direction_type, account_id, `state`) USING BTREE,
    UNIQUE KEY udx_order_u ( unique_id, direction_type, account_id, `state`) USING BTREE,
    KEY                 idx_batch_id ( batch_id ) USING BTREE,
    KEY                 idx_order_credited ( account_id, credited_date ) USING BTREE,
    KEY                 idx_order_apply ( account_id, apply_date ) USING BTREE,
    KEY                 idx_sub_merchant_id ( sub_merchant_id ,apply_date) USING BTREE,
    KEY                 idx_sub_account_id ( sub_account_id ,apply_date) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'customize batch withdrawal transaction detail(byd)';