CREATE TABLE `sub_account`
(
    `id`              bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
    `merchant_id`     bigint         NOT NULL COMMENT 'merchant id',
    `sub_merchant_id` varchar(64)    NOT NULL COMMENT 'sub merchant id',
    `account_ids`     json           NOT NULL COMMENT 'owner account list',
    `country_code`    varchar(2)     NOT NULL COMMENT 'CountryCodeEnum',
    `balance`         decimal(26, 0) NOT NULL DEFAULT '0' COMMENT 'balance',
    `currency`        varchar(3)     NOT NULL COMMENT 'balance pool currency properties',
    `timezone`        varchar(8)              DEFAULT NULL COMMENT 'local time zone',
    `timezone_name`   varchar(64)             DEFAULT '',
    `created_time`    datetime                DEFAULT NULL,
    `updated_time`    datetime                DEFAULT NULL,
    `created_by`      bigint                  DEFAULT '0',
    `updated_by`      bigint                  DEFAULT '0',
    `version`         bigint unsigned DEFAULT '1' COMMENT 'optimistic locking',
    `del_flag`        tinyint(1) NOT NULL DEFAULT '0' COMMENT '0-normal，1-delete',
    `remark`          varchar(200)            DEFAULT '' COMMENT 'remark',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `idx_merchant_sub_merchant` (`merchant_id`,`country_code`,`sub_merchant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='sub account';

CREATE TABLE `sub_account_statement`
(
    `id`                    bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
    `merchant_id`           bigint      NOT NULL COMMENT 'merchant id',
    `sub_merchant_id`       varchar(64) NOT NULL COMMENT 'sub merchant id',
    `account_id`            bigint      NOT NULL COMMENT 'account id',
    `sub_account_id`        bigint      NOT NULL COMMENT 'sub account id',
    `transaction_id`        bigint      NOT NULL COMMENT 'fk tack_id',
    `country_code`          varchar(2)  NOT NULL COMMENT 'CountryCodeEnum',
    `transaction_type_code` varchar(32) NOT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
    `product_code`          varchar(32)          DEFAULT NULL COMMENT 'ProductCodeEnum',
    `business_type`         varchar(32)          DEFAULT NULL COMMENT 'business_type : TRANSACTION, TOPUP, TRANSFER_OUT, REFUND',
    `direction_type`        varchar(32)          DEFAULT NULL COMMENT 'DirectionTypeEnum: SETTLED/REFUND/CHARGE_BACK',
    `amount_pon`            decimal(2, 0)        DEFAULT NULL COMMENT 'positive or negative; positive :+1, negative:-1',
    `amount`                decimal(26, 0)       DEFAULT NULL COMMENT 'save integer type, default to penny',
    `currency`              varchar(3)           DEFAULT NULL,
    `start_balance`         decimal(26, 0)       DEFAULT NULL,
    `end_balance`           decimal(26, 0)       DEFAULT NULL,
    `transaction_time`      timestamp NULL DEFAULT NULL,
    `transaction_timestamp` int unsigned DEFAULT '0',
    `settle_time`           timestamp NULL DEFAULT NULL,
    `created_time`          datetime             DEFAULT CURRENT_TIMESTAMP,
    `updated_time`          datetime             DEFAULT CURRENT_TIMESTAMP,
    `created_by`            bigint               DEFAULT 0,
    `updated_by`            bigint               DEFAULT 0,
    `version`               int                  DEFAULT '1' COMMENT 'optimistic locking',
    `del_flag`              tinyint     NOT NULL DEFAULT '0' COMMENT '0-normal，1-delete',
    PRIMARY KEY (`id`) USING BTREE,
    KEY                     `idx_transaction_id` (`transaction_id`) USING BTREE,
    KEY                     `idx_account_id_transaction_timestamp` (`sub_account_id`,`transaction_timestamp`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='sub account statement';

CREATE TABLE `sub_account_daily_bill`
(
    `id`                       bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
    `merchant_id`              bigint      NOT NULL COMMENT 'merchant id',
    `country_code`             varchar(3)  NOT NULL COMMENT 'CountryCodeEnum',
    `sub_merchant_id`          varchar(64) NOT NULL COMMENT 'sub merchant id',
    `sub_account_id`           bigint      NOT NULL COMMENT 'sub account id',
    `bill_month`               int         NOT NULL COMMENT 'yyyyMM',
    `bill_date`                date        NOT NULL COMMENT 'yyyyMMdd',
    `start_balance`            decimal(26, 0)       DEFAULT '0',
    `happen_amount`            decimal(26, 0)       DEFAULT '0',
    `end_balance`              decimal(26, 0)       DEFAULT '0',
    `payin_transaction_count`  int unsigned DEFAULT '0' COMMENT 'payin transaction number',
    `payin_settlement_amount`  decimal(26, 0)       DEFAULT '0' COMMENT 'payin settlement amount',
    `payin_transaction_fee`    decimal(26, 0)       DEFAULT '0' COMMENT 'payin transaction fee, unit: cent(keep 0 decimal places)',
    `payin_transaction_tax`    decimal(26, 0)       DEFAULT '0' COMMENT 'payin transaction tax, unit: cent(keep 0 decimal places)',
    `payout_transaction_count` int unsigned DEFAULT '0' COMMENT 'payout number of transactions current day',
    `payout_settlement_amount` decimal(26, 0)       DEFAULT '0' COMMENT 'original transaction order amount',
    `payout_transaction_fee`   decimal(26, 0)       DEFAULT '0' COMMENT 'settled amount, unit: cent(keep 0 decimal places)',
    `payout_transaction_tax`   decimal(26, 0)       DEFAULT '0' COMMENT 'settled amount, unit: cent(keep 0 decimal places)',
    `topup_amount`             decimal(26, 0)       DEFAULT '0' COMMENT 'topup amount',
    `topup_count`              int unsigned DEFAULT '0' COMMENT 'topup count',
    `topup_fee`                decimal(26, 0)       DEFAULT '0' COMMENT 'topup fee',
    `topup_tax`                decimal(26, 0)       DEFAULT '0' COMMENT 'topup tax',
    `transfer_amount`          decimal(26, 0)       DEFAULT '0' COMMENT 'transfer amount',
    `transfer_count`           int unsigned DEFAULT '0' COMMENT 'transfer count',
    `transfer_fee`             decimal(26, 0)       DEFAULT '0' COMMENT 'transfer fee',
    `transfer_tax`             decimal(26, 0)       DEFAULT '0' COMMENT 'transfer tax',
    `exchange_amount`          decimal(26, 0)       DEFAULT '0' COMMENT 'exchange amount',
    `exchange_count`           int unsigned DEFAULT '0' COMMENT 'exchange count',
    `exchange_fee`             decimal(26, 0)       DEFAULT '0' COMMENT 'exchange fee',
    `exchange_tax`             decimal(26, 0)       DEFAULT '0' COMMENT 'exchange tax',
    `adjustment_amount`        decimal(26, 0)       DEFAULT '0' COMMENT 'adjustment amount',
    `adjustment_count`         int                  DEFAULT '0' COMMENT 'adjustment count',
    `currency`                 varchar(3)           DEFAULT NULL COMMENT 'account currency',
    `created_time`             datetime             DEFAULT NULL,
    `updated_time`             datetime             DEFAULT NULL,
    `created_by`               bigint               DEFAULT '0',
    `updated_by`               bigint               DEFAULT '0',
    `version`                  int                  DEFAULT '1' COMMENT 'optimistic locking',
    `del_flag`                 tinyint     NOT NULL DEFAULT '0' COMMENT '0-normal，1-delete',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `idx_sub_account_id` (`sub_account_id`,`bill_date`) USING BTREE,
    KEY                        `idx_merchant_country_bill_date` (`merchant_id`,`sub_merchant_id`,`country_code`,`bill_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='sub_account_daily_bill';