apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-uat

commonLabels:
  app.kubernetes.io/name: app-accounting-service-statement

commonAnnotations:
  kubernetes.io/change-cause: NEWTAGNAME

images:
  - name: 398186320513.dkr.ecr.ap-southeast-1.amazonaws.com/liquido-service-accounting-statement
    newName: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/liquido-service-accounting-statement-uat
    newTag: NEWTAGNAME

replicas:
  - name: accounting-service-statement-deployment
    count: 2

resources:
  - ../../base

patches:
  - path: ./set_memory.yaml



