CREATE TABLE `payment_link`
(
    `id`                    bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
    `link_id`               varchar(128)   NOT NULL COMMENT 'payment link id',
    `merchant_reference`    varchar(128)            DEFAULT NULL COMMENT 'merchant order id',
    `merchant_code`         varchar(128)   NOT NULL COMMENT 'merchant code',
    `country_code`          varchar(2)     NOT NULL COMMENT 'CountryCodeEnum',
    `transaction_type_code` varchar(32)    NOT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
    `product_code`          varchar(32) NULL DEFAULT NULL COMMENT 'ProductCodeEnum',
    `amount`                decimal(26, 0) NOT NULL,
    `currency`              varchar(3)     NOT NULL,
    `payment_status`        varchar(32)    NOT NULL COMMENT 'PaymentLinkStatusEnum: INITIAL_STATUS/IN_PROGRESS/SETTLED/FAILED',
    `settled_unique_id`     varchar(128) NULL DEFAULT NULL COMMENT 'settled unique id',
    `submit_time`           timestamp      NOT NULL COMMENT 'submit time (UTC 0)',
    `submit_timestamp`      int            NOT NULL COMMENT 'submit timestamp (second)',
    `transaction_time`      timestamp NULL DEFAULT NULL COMMENT 'transaction time (UTC 0)',
    `transaction_timestamp` int NULL DEFAULT NULL COMMENT 'transaction timestamp (second)',
    `refund_status`         varchar(32) NULL DEFAULT NULL COMMENT 'PaymentLinkStatusEnum: INITIAL_STATUS/IN_PROGRESS/SETTLED/FAILED',
    `refund_amount`         decimal(26, 0) NOT NULL DEFAULT 0,
    `refunded_unique_id`    varchar(128) NULL DEFAULT NULL COMMENT 'refunded unique id',
    `refund_time`           timestamp NULL DEFAULT NULL COMMENT 'refund time (UTC 0)',
    `refund_timestamp`      int NULL DEFAULT NULL COMMENT 'refund timestamp (second)',
    `event_timestamp`       int            NOT NULL COMMENT 'event timestamp (second)',
    `user_email`            varchar(128) NULL DEFAULT NULL COMMENT 'user email',
    `user_phone`            varchar(128) NULL DEFAULT NULL COMMENT 'user phone',
    `created_time`          datetime                DEFAULT NULL,
    `updated_time`          datetime                DEFAULT NULL,
    `created_by`            bigint                  DEFAULT '0',
    `updated_by`            bigint                  DEFAULT '0',
    `version`               int            NOT NULL DEFAULT '0' COMMENT 'optimistic locking 0:normal, 1:locked',
    `del_flag`              tinyint(1) NOT NULL DEFAULT '0' COMMENT '0-normal，1-delete',
    `remark`                varchar(200)            DEFAULT '' COMMENT 'remark',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `idx_payment_link_id` (`link_id`) USING BTREE,
    UNIQUE KEY `idx_merchant_reference` (`merchant_reference`) USING BTREE,
    KEY                     `idx_event_timestamp` (`event_timestamp`) USING BTREE,
    KEY                     `idx_page` (`merchant_code`,`country_code`,`transaction_type_code`,`submit_timestamp`,`payment_status`,`refund_status`,`del_flag`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='payment_link';