CREATE TABLE `service_accounting_worker`.`defense_order`
(
    `id`                    bigint(0) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key Id',
    `original_id`           bigint(0) NOT NULL COMMENT 'original id',
    `unique_id`             varchar(128)   NOT NULL COMMENT 'from global transaction system uniqueId, reference task_fee_calculation.unique_id',
    `merchant_id`           bigint(0) NOT NULL COMMENT 'fk',
    `account_id`            bigint(0) NOT NULL COMMENT 'account id',
    `transaction_type_code` varchar(32)    NOT NULL COMMENT 'TransactionTypeCodeEnum: PAY_IN/PAY_OUT/MARKET_PLACE_ORDERS',
    `product_code`          varchar(32)    NOT NULL COMMENT 'ProductCodeEnum: SPEI/TED/PIX/CREDIT_CARD/ELO_CREDIT_CARD/BOLETO/OXXO/GIFTCARD/TOPUP/UTILITY',
    `payment_amount`        decimal(26, 0) NOT NULL COMMENT 'Original transaction amount, unit: cent',
    `dispute_amount`        decimal(26, 0) NOT NULL DEFAULT 0 COMMENT 'transaction amount, unit: cent',
    `currency`              varchar(3)     NOT NULL COMMENT 'transaction currency',
    `card_number`           varchar(64) NULL DEFAULT NULL,
    `payment_time`          datetime(0) NOT NULL COMMENT 'Original order transaction time',
    `dispute_time`          datetime(0) NOT NULL COMMENT 'UTC+0',
    `chargeback_status`     varchar(32)    NOT NULL COMMENT 'original status/(OPEN,REVIEW,REVERSED,LOSE)',
    `defense_status`        varchar(32)    NOT NULL COMMENT 'status/(chargeback、under defense、defense won、defense lost)',
    `defense_time`          datetime(0) NULL DEFAULT NULL COMMENT 'defense time',
    `days_left_to_defend`   int(0) NOT NULL COMMENT 'defend count down',
    `defense_deadline`      datetime(0) NOT NULL COMMENT 'defense deadline',
    `dispute_reason`        varchar(400) NULL DEFAULT NULL COMMENT 'dispute_reason',
    `defense_description`   varchar(400) NULL DEFAULT NULL COMMENT 'defense description',
    `defense_appendix_ids`  json NULL COMMENT 'defense appendix',
    `created_time`          datetime(0) NULL DEFAULT NULL,
    `updated_time`          datetime(0) NULL DEFAULT NULL,
    `created_by`            bigint(0) NULL DEFAULT 0,
    `updated_by`            bigint(0) NULL DEFAULT 0,
    `version`               int(0) NULL DEFAULT 1 COMMENT 'optimistic locking',
    `del_flag`              tinyint(0) NOT NULL DEFAULT 0 COMMENT '0-normal，1-delete',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `udx_unique_id`(`unique_id`) USING BTREE,
    INDEX                   `idx_account_dispute_time`(`account_id`, `dispute_time`) USING BTREE
)ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'defense_order' ROW_FORMAT = DYNAMIC;;