update service_accounting_base.merchant set industry = 'PSP'  where code = 'aldeavip';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'aldeavip_sas';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'blind_creators';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'blind_creators_shopify';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'didi';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'didicredit';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'eecom';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'eecom_gadgets_and_fun';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'eecom_getfit';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'eecom_luvit';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'geewallet';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'foxnovel';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'globalpix';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'globalpix_mx';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'doowin';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'incoservi';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'yunds';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'intervalo';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'intervalo_sfno1';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'servitogo';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'clinclin';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'fcube';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'yundsnew';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'jingle_tiger';
update service_accounting_base.merchant set industry = 'Social Platform'  where code = 'kwai';
update service_accounting_base.merchant set industry = 'Social Platform'  where code = 'kwai_sports';
update service_accounting_base.merchant set industry = 'Social Platform'  where code = 'kwai_largeticket';
update service_accounting_base.merchant set industry = 'Social Platform'  where code = 'kwai_livestream';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'lexin';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'lexin_uat';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'photonpay';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'photonpay_2';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'planckx_v2';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'planckx';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'recopos';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'recopos1';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_mifectivo';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_creditt';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_nettlan';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_nettlan_2';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_nettlan_3';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_sofom_mifectivo';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_sofom_mifectivo_1';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_topline_mx';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_co';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_rapicredi';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_suplerplata';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_if';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_yumilite';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_yumirapido';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_sofom_mifectivo_2';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'sailone_topline_new';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'zwolfre';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'infolombo';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'rivotech';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'spaceera';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'telong';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'cashy';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'crp';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'crp2';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'oneway_tech';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'vita_service';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'telong_mx';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'wiio';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'wiio_tudovasio';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'wire4';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'wire4_usd';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'zeropoint';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'zeropoint_co';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'zeropoint_mx';
update service_accounting_base.merchant set industry = 'FinTech'  where code = '2x3';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = '360_slim';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'allure';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'artibiana';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'ats';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'bacos';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'buk';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'c_mobile';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'calii';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'carbo_products';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'cheng_fan';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'chenrui';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'cider';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'clipspay';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'colorette_makeup';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'confiabogado';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'crisobela';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'cryptobank';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'dahl';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'dayu_space';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'dr_lingerie';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'dropkickz';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'dukpay';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'dune_finance';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'durablewig';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'eastorm';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'elaworld';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'enovei';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'eskimo';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'fajas_mariae';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'farmacia_san_jorge';
update service_accounting_base.merchant set industry = 'Digital Service'  where code = 'farol_tecnologia';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'fatpay_retail';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'fintopia';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'garnet';
update service_accounting_base.merchant set industry = 'Digital Service'  where code = 'giftcard';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'gracies';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'gutierrez_group';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'gwm';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'habibi_plantitas';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'haishi';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'harbour_beach';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'hector_renteria_zavala';
update service_accounting_base.merchant set industry = 'Digital Service'  where code = 'hermes_music';
update service_accounting_base.merchant set industry = 'Mobile Entertainment'  where code = 'hilive';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'hogaru';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'hotel_574';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'hoteleria_mzt';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'hung_hing';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'ientc';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'ighs';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'insights';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'iotac';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'jc';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'jdg_law_advisors';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'jm_imports';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'jnt';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'juggo';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'killb';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'laika';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'lk_sneakers';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'luis_osvaldo_garcia_cruz';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'lypsa';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'maaji';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'maaji_mercado_blanco';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'magic_box';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'mamotest';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'mangocash';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'maralago';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'marena';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'marest';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'marquisse';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'memepay';
update service_accounting_base.merchant set industry = 'Gaming'  where code = 'migtech';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'milexcess';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'milian';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'mis_bebes';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'muy_bonita';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'nanopay';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'nanxi';
update service_accounting_base.merchant set industry = 'Mobile Entertainment'  where code = 'navigatorx';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'nebulapart';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'neopay';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'nudigital';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'nudos';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'nuzo';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'octopus_exportaciones';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'okboy';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'om_strategic_consulting';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'onewallet';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'ontrack';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'orderplus';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'oriental_express';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'oxio';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'pari';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'payermax';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'paynau';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'payssion';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'pixeltec';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'planet_collection';
update service_accounting_base.merchant set industry = 'Gaming'  where code = 'pub_games';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'qbit';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'rusemex';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'shift4';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'skopa';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'pronagos';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'spaceyy';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'starmark_express';
update service_accounting_base.merchant set industry = 'Digital Service'  where code = 'starmoon';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'sudutech';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'sulkin';
update service_accounting_base.merchant set industry = 'Digital Service'  where code = 'talkguest';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'tangerine';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'tani_salud';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'tejidos_anymax';
update service_accounting_base.merchant set industry = 'Digital Service'  where code = 'tf';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'thunder_wing';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'tikipay';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'tiui';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'tocartagena';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'tuna';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'uc_pay';
update service_accounting_base.merchant set industry = 'PSP'  where code = 'uc_pay_api';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'undostres';
update service_accounting_base.merchant set industry = 'Retail Digitization'  where code = 'vattea';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'vdt_logistica';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'w_caf';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'wagon';
update service_accounting_base.merchant set industry = 'Digital Service'  where code = 'wati_io';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'we_love_luana';
update service_accounting_base.merchant set industry = 'Gaming'  where code = 'wegital';
update service_accounting_base.merchant set industry = 'FinTech'  where code = 'wemg';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'wild_time_colombia';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'winnerz_store';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'woba';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'cheng_fan';
update service_accounting_base.merchant set industry = 'Ecommerce'  where code = 'ziyouke';
update service_accounting_base.merchant set industry = 'Gig Economy'  where code = 'zubale';

update service_accounting_base.merchant set industry = 'Fintech' where code = 'nanopay_arcus';
update service_accounting_base.merchant set industry = 'Retail Digitization' where code = 'gold_cheer';
update service_accounting_base.merchant set industry = 'Fintech' where code = 'rusemex_2';
update service_accounting_base.merchant set industry = 'Ecommerce' where code = 'mer';
update service_accounting_base.merchant set industry = 'Retail Digitization' where code = 'my_gwm';
update service_accounting_base.merchant set industry = 'Ecommerce' where code = 'givelo';
