package com.liquido.core.common.snowflake;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.security.SecureRandom;

import com.liquido.core.common.exception.FrameworkExceptionCode;
import com.liquido.core.common.logger.LogWrapper;
import com.liquido.core.configuration.CommonProperties;

import lombok.extern.slf4j.Slf4j;

/**
 * The initial timestamp of the id generated by the snowflake algorithm is 2022-01-01
 * |-------------31-bits Timestamp-----------| |---16-bit machine-----| |-----17-bit concurrency---|
 * 0000000000 0000000000 0000000000 0 0000000000 000000 0000000000 0000000<br>
 */
@Slf4j
public class SnowflakeIdK8S {

    /**
     * machine identification number
     */
    private static final long workerIdBits = 16L;
    /**
     * Serial number identification digits
     */
    private static final long sequenceBits = 17L;
    /**
     * Machine ID Max
     */
    private static final long maxWorkerId = -1L ^ (-1L << workerIdBits);
    /**
     * Serial Number ID Maximum
     */
    private static final long sequenceMask = -1L ^ (-1L << sequenceBits);
    private static final long workerIdShift = sequenceBits;
    private static final long timestampLeftShift = sequenceBits + workerIdBits;
    /**
     * base time 2022-01-01
     * 1640966400
     */
    private static final long epoch = 1640966400L;

    private static long lastTimestamp = -1L;

    private static long sequence = 0L;

    /**
     * The number of machines, 0-65535, can be expanded up to the 65536th machine
     */
    private static long workerId = 0L;

    /**
     * Snowflake algorithm is not enabled by default
     */
    private static boolean enabled = false;

    public static void init(final CommonProperties commonProperties) {
        log.info(LogWrapper.op("SnowflakeIdUtil.init").wrap("commonProperties.getSnowflakeMode()",
                commonProperties.getSnowFlake().getMode()).toString());
        try {
            switch (commonProperties.getSnowFlake().getMode()) {
                case HOST:
                    workerId = generateWorkerIdByHost();
                    break;
                case IPV4:
                    workerId = generateWorkerIdByIpv4();
                    break;
                case CONFIG:
                    workerId = commonProperties.getSnowFlake().getWorkerId();
                    break;
                default:
                    workerId = generateWorkerIdByHost();
                    break;
            }
        } catch (Exception e) {
            throw FrameworkExceptionCode.SNOWFLAKE_CENTER_ID_ERROR.exception(e);
        }

        if (workerId > maxWorkerId) {
            throw FrameworkExceptionCode.SNOWFLAKE_WORKER_ID_ERROR.exception();
        }

        enabled = true;
        log.info(LogWrapper.op("SnowflakeIdK8S.init")
                .wrap("enabled", enabled)
                .wrap("workerId", workerId).toString());
    }

    public static long generate() {
        if (!enabled) {
            throw FrameworkExceptionCode.SNOWFLAKE_SWITCH_OFF.exception();
        }
        return nextId();
    }

    private static synchronized long nextId() {

        long timestamp = timeGen();
        if (timestamp < lastTimestamp) {
            if (timestamp < lastTimestamp) {
                try {
                    throw new Exception("Clock moved backwards.  Refusing to generate id for "
                            + (lastTimestamp - timestamp) + " milliseconds");
                } catch (Exception e) {
                    log.error("SnowflakeIdK8S generate nextId error:", e);
                }
            } else {
                return generate();
            }
        }

        if (lastTimestamp == timestamp) {
            sequence = (sequence + 1) & sequenceMask;
            if (sequence == 0) {
                timestamp = tailNextMillis(lastTimestamp);
            }
        } else {
            sequence = new SecureRandom().nextInt(10);
        }

        lastTimestamp = timestamp;

        return ((timestamp - epoch) << timestampLeftShift)
                | (workerId << workerIdShift)
                | sequence;
    }

    /**
     * To prevent the generated time from being smaller
     * than the previous time (due to NTP callbacks, etc.), keep the incremental trend.
     */
    private static long tailNextMillis(final long lastTimestamp) {
        long timestamp = timeGen();
        while (timestamp <= lastTimestamp) {
            timestamp = timeGen();
        }

        return timestamp;
    }

    /**
     * Get the current timestamp
     */
    protected static long timeGen() {
        return System.currentTimeMillis() / 1000L;
    }

    /**
     * generate worker-id by ipv4
     *
     * @return long
     */
    private static long generateWorkerIdByIpv4() {
        final InetAddress address;
        try {
            address = InetAddress.getLocalHost();
        } catch (final UnknownHostException e) {
            throw FrameworkExceptionCode.SNOWFLAKE_NET_ADDRESS_ERROR.exception();
        }

        byte[] ipAddressByteArray = address.getAddress();

        return ((ipAddressByteArray[ipAddressByteArray.length - 2] & 0xFF) << Byte.SIZE)
                + (ipAddressByteArray[ipAddressByteArray.length - 1] & 0xFF);
    }

    /**
     * generate worker-id by host
     *
     * @return long
     */
    private static long generateWorkerIdByHost() {
        final InetAddress address;
        final long workerId;
        try {
            address = InetAddress.getLocalHost();
        } catch (final UnknownHostException e) {
            throw new IllegalStateException(
                    "Cannot get LocalHost InetAddress, please check your network!");
        }

        final String hostName = address.getHostName();
        log.info(LogWrapper.op("SnowflakeIdUtil.generateWorkerIdByHost").wrap("hostName", hostName)
                .toString());

        try {
            final String lastHostName = hostName.substring(hostName.lastIndexOf("-") + 1);
            log.info(LogWrapper.op("SnowflakeIdUtil.generateWorkerIdByHost")
                    .wrap("lastHostName", lastHostName).toString());

            workerId = Long.valueOf(lastHostName);
            log.info(LogWrapper.op("SnowflakeIdUtil.generateWorkerIdByHost")
                    .wrap("workerId", workerId).toString());
        } catch (final NumberFormatException e) {
            throw new IllegalArgumentException(
                    String.format("Wrong hostname:%s, hostname must be end with number!",
                            hostName));
        }

        return workerId;
    }

    /**
     * Get the timestamp corresponding to the snowflake algorithm
     *
     * @param snowflakeId snowflakeId
     */
    public static long getTimestampBySnowflakeId(long snowflakeId) {
        long result = (snowflakeId >> timestampLeftShift) + epoch;
        return result * 1000;
    }
}
