apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: NAMESPACE
  name: accounting-service-worker-deployment
spec:
  template:
    spec:
      containers:
        - name: app-accounting-service-worker
          resources:
            limits:
              # 2Gi
              memory: "2048Mi"
            requests:
              # 1.75Gi
              memory: "1792Mi"
